#!/bin/bash

# cd into this directory, so the log file can be a relative path
cd "$( dirname "$0" )"

LOGFILE=update.log

echo >> $LOGFILE # add an empty line to the log

/usr/local/bin/wget --timestamping http://winhelp2002.mvps.org/hosts.zip >> $LOGFILE

[[ -f HOSTS ]] || touch -t 200001010101 HOSTS

unzip -afoq hosts.zip >> $LOGFILE

sed -e '/localhost/d' \
    -e 's/ *#.*//'    \
    -e 's/[ ^I]*$//g' \
    -e '/^\s*$/d'     \
    HOSTS > hosts.block

cp hosts.block /etc/hosts.block

cd /etc

[[ -f hosts.local ]] || cp hosts hosts.local

cat hosts.local hosts.block > hosts
